
# This file is automatically generated, you probably don't want to edit this

frequenciesOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "frequenciesOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            yscale = FALSE, ...) {

            super$initialize(
                package="biol215",
                name="frequencies",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep)
            private$..yscale <- jmvcore::OptionBool$new(
                "yscale",
                yscale,
                default=FALSE)

            self$.addOption(private$..dep)
            self$.addOption(private$..yscale)
        }),
    active = list(
        dep = function() private$..dep$value,
        yscale = function() private$..yscale$value),
    private = list(
        ..dep = NA,
        ..yscale = NA)
)

frequenciesResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "frequenciesResults",
    inherit = jmvcore::Group,
    active = list(
        freqs = function() private$.items[["freqs"]],
        countbar = function() private$.items[["countbar"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Tally frequencies")
            self$add(jmvcore::Table$new(
                options=options,
                name="freqs",
                title="Frequencies of levels",
                rows=0,
                columns=list(
                    list(
                        `name`="levels", 
                        `title`="Levels", 
                        `type`="text"),
                    list(
                        `name`="freq", 
                        `type`="integer", 
                        `title`="Frequency"),
                    list(
                        `name`="rfreq", 
                        `title`="Relative frequency", 
                        `type`="number"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="countbar",
                title="Bar chart of counts",
                width=400,
                height=300,
                renderFun=".plot"))}))

frequenciesBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "frequenciesBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "biol215",
                name = "frequencies",
                version = c(1,0,0),
                options = options,
                results = frequenciesResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Tally frequencies
#'
#' 
#' @param data .
#' @param dep .
#' @param yscale .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$freqs} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$countbar} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$freqs$asDF}
#'
#' \code{as.data.frame(results$freqs)}
#'
#' @export
frequencies <- function(
    data,
    dep,
    yscale = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("frequencies requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL))


    options <- frequenciesOptions$new(
        dep = dep,
        yscale = yscale)

    analysis <- frequenciesClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

