
# This file is automatically generated, you probably don't want to edit this

histogramOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "histogramOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            group = NULL,
            bins = 10,
            sturges = FALSE,
            yscale = "count", ...) {

            super$initialize(
                package="biol215",
                name="histogram",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep)
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group)
            private$..bins <- jmvcore::OptionNumber$new(
                "bins",
                bins,
                default=10)
            private$..sturges <- jmvcore::OptionBool$new(
                "sturges",
                sturges,
                default=FALSE)
            private$..yscale <- jmvcore::OptionList$new(
                "yscale",
                yscale,
                options=list(
                    "count",
                    "relfreq"),
                default="count")

            self$.addOption(private$..dep)
            self$.addOption(private$..group)
            self$.addOption(private$..bins)
            self$.addOption(private$..sturges)
            self$.addOption(private$..yscale)
        }),
    active = list(
        dep = function() private$..dep$value,
        group = function() private$..group$value,
        bins = function() private$..bins$value,
        sturges = function() private$..sturges$value,
        yscale = function() private$..yscale$value),
    private = list(
        ..dep = NA,
        ..group = NA,
        ..bins = NA,
        ..sturges = NA,
        ..yscale = NA)
)

histogramResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "histogramResults",
    inherit = jmvcore::Group,
    active = list(
        histo = function() private$.items[["histo"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Histogram")
            self$add(jmvcore::Image$new(
                options=options,
                name="histo",
                title="Histogram",
                width=400,
                height=300,
                renderFun=".plot"))}))

histogramBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "histogramBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "biol215",
                name = "histogram",
                version = c(1,0,0),
                options = options,
                results = histogramResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Histogram
#'
#' 
#' @param data .
#' @param dep .
#' @param group .
#' @param bins .
#' @param sturges .
#' @param yscale .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$histo} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
histogram <- function(
    data,
    dep,
    group,
    bins = 10,
    sturges = FALSE,
    yscale = "count") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("histogram requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(group), group, NULL))


    options <- histogramOptions$new(
        dep = dep,
        group = group,
        bins = bins,
        sturges = sturges,
        yscale = yscale)

    analysis <- histogramClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

