
# This file is automatically generated, you probably don't want to edit this

indvalplotOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "indvalplotOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            group = NULL,
            showmean = FALSE,
            showbars = FALSE,
            jitter = FALSE, ...) {

            super$initialize(
                package="biol215",
                name="indvalplot",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep)
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group)
            private$..showmean <- jmvcore::OptionBool$new(
                "showmean",
                showmean,
                default=FALSE)
            private$..showbars <- jmvcore::OptionBool$new(
                "showbars",
                showbars,
                default=FALSE)
            private$..jitter <- jmvcore::OptionBool$new(
                "jitter",
                jitter,
                default=FALSE)

            self$.addOption(private$..dep)
            self$.addOption(private$..group)
            self$.addOption(private$..showmean)
            self$.addOption(private$..showbars)
            self$.addOption(private$..jitter)
        }),
    active = list(
        dep = function() private$..dep$value,
        group = function() private$..group$value,
        showmean = function() private$..showmean$value,
        showbars = function() private$..showbars$value,
        jitter = function() private$..jitter$value),
    private = list(
        ..dep = NA,
        ..group = NA,
        ..showmean = NA,
        ..showbars = NA,
        ..jitter = NA)
)

indvalplotResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "indvalplotResults",
    inherit = jmvcore::Group,
    active = list(
        indvalplot = function() private$.items[["indvalplot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Individual value plot")
            self$add(jmvcore::Image$new(
                options=options,
                name="indvalplot",
                title="Individual value plot",
                width=400,
                height=300,
                renderFun=".plot"))}))

indvalplotBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "indvalplotBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "biol215",
                name = "indvalplot",
                version = c(1,0,0),
                options = options,
                results = indvalplotResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Individual value plot
#'
#' 
#' @param data .
#' @param dep .
#' @param group .
#' @param showmean .
#' @param showbars .
#' @param jitter .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$indvalplot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
indvalplot <- function(
    data,
    dep,
    group,
    showmean = FALSE,
    showbars = FALSE,
    jitter = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("indvalplot requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(group), group, NULL))


    options <- indvalplotOptions$new(
        dep = dep,
        group = group,
        showmean = showmean,
        showbars = showbars,
        jitter = jitter)

    analysis <- indvalplotClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

