
# This file is automatically generated, you probably don't want to edit this

intervalplotOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "intervalplotOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            group = NULL,
            inttype = "stder", ...) {

            super$initialize(
                package="biol215",
                name="intervalplot",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep)
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group)
            private$..inttype <- jmvcore::OptionList$new(
                "inttype",
                inttype,
                options=list(
                    "stder",
                    "confint"),
                default="stder")

            self$.addOption(private$..dep)
            self$.addOption(private$..group)
            self$.addOption(private$..inttype)
        }),
    active = list(
        dep = function() private$..dep$value,
        group = function() private$..group$value,
        inttype = function() private$..inttype$value),
    private = list(
        ..dep = NA,
        ..group = NA,
        ..inttype = NA)
)

intervalplotResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "intervalplotResults",
    inherit = jmvcore::Group,
    active = list(
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Interval Plot")
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Interval Plot",
                width=400,
                height=300,
                renderFun=".plot"))}))

intervalplotBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "intervalplotBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "biol215",
                name = "intervalplot",
                version = c(1,0,1),
                options = options,
                results = intervalplotResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Interval Plot
#'
#' 
#' @param data .
#' @param dep .
#' @param group .
#' @param inttype .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
intervalplot <- function(
    data,
    dep,
    group,
    inttype = "stder") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("intervalplot requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(group), group, NULL))


    options <- intervalplotOptions$new(
        dep = dep,
        group = group,
        inttype = inttype)

    analysis <- intervalplotClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

