
# This file is automatically generated, you probably don't want to edit this

pieOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "pieOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            freq = NULL, ...) {

            super$initialize(
                package="biol215",
                name="pie",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep)
            private$..freq <- jmvcore::OptionVariable$new(
                "freq",
                freq)

            self$.addOption(private$..dep)
            self$.addOption(private$..freq)
        }),
    active = list(
        dep = function() private$..dep$value,
        freq = function() private$..freq$value),
    private = list(
        ..dep = NA,
        ..freq = NA)
)

pieResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "pieResults",
    inherit = jmvcore::Group,
    active = list(
        piefreqs = function() private$.items[["piefreqs"]],
        pie = function() private$.items[["pie"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Pie chart")
            self$add(jmvcore::Table$new(
                options=options,
                name="piefreqs",
                title="Frequencies and relative frequencies of levels",
                rows=0,
                columns=list(
                    list(
                        `name`="levels", 
                        `title`="Levels", 
                        `type`="text"),
                    list(
                        `name`="freq", 
                        `type`="integer", 
                        `title`="Frequency"),
                    list(
                        `name`="rfreq", 
                        `title`="Relative frequency", 
                        `type`="number"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="pie",
                title="Pie chart of relative frequencies",
                width=400,
                height=300,
                renderFun=".plot"))}))

pieBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "pieBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "biol215",
                name = "pie",
                version = c(1,0,0),
                options = options,
                results = pieResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Pie chart
#'
#' 
#' @param data .
#' @param dep .
#' @param freq .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$piefreqs} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$pie} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$piefreqs$asDF}
#'
#' \code{as.data.frame(results$piefreqs)}
#'
#' @export
pie <- function(
    data,
    dep,
    freq) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("pie requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if ( ! missing(freq)) freq <- jmvcore::resolveQuo(jmvcore::enquo(freq))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(freq), freq, NULL))


    options <- pieOptions$new(
        dep = dep,
        freq = freq)

    analysis <- pieClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

