
# This file is automatically generated, you probably don't want to edit this

qqplotOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "qqplotOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            group = NULL, ...) {

            super$initialize(
                package="biol215",
                name="qqplot",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep)
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group)

            self$.addOption(private$..dep)
            self$.addOption(private$..group)
        }),
    active = list(
        dep = function() private$..dep$value,
        group = function() private$..group$value),
    private = list(
        ..dep = NA,
        ..group = NA)
)

qqplotResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "qqplotResults",
    inherit = jmvcore::Group,
    active = list(
        normtest = function() private$.items[["normtest"]],
        qqplot = function() private$.items[["qqplot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Normal probability plot")
            self$add(jmvcore::Table$new(
                options=options,
                name="normtest",
                title="Shapiro-Wilks normality test",
                rows=0,
                columns=list(
                    list(
                        `name`="levels", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="W", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="qqplot",
                title="Normal quantile comparison plot",
                width=400,
                height=300,
                renderFun=".plot"))}))

qqplotBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "qqplotBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "biol215",
                name = "qqplot",
                version = c(1,0,0),
                options = options,
                results = qqplotResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Normal probability plot
#'
#' 
#' @param data .
#' @param dep .
#' @param group .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$normtest} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$qqplot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$normtest$asDF}
#'
#' \code{as.data.frame(results$normtest)}
#'
#' @export
qqplot <- function(
    data,
    dep,
    group) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("qqplot requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(group), group, NULL))


    options <- qqplotOptions$new(
        dep = dep,
        group = group)

    analysis <- qqplotClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

