
# This file is automatically generated, you probably don't want to edit this

regplotOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "regplotOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            indep = NULL, ...) {

            super$initialize(
                package="biol215",
                name="regplot",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep)
            private$..indep <- jmvcore::OptionVariable$new(
                "indep",
                indep)

            self$.addOption(private$..dep)
            self$.addOption(private$..indep)
        }),
    active = list(
        dep = function() private$..dep$value,
        indep = function() private$..indep$value),
    private = list(
        ..dep = NA,
        ..indep = NA)
)

regplotResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "regplotResults",
    inherit = jmvcore::Group,
    active = list(
        scatter = function() private$.items[["scatter"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Scatter plot with regression line")
            self$add(jmvcore::Image$new(
                options=options,
                name="scatter",
                title="Scatter plot",
                width=400,
                height=300,
                renderFun=".plot"))}))

regplotBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "regplotBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "biol215",
                name = "regplot",
                version = c(1,0,0),
                options = options,
                results = regplotResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Scatter Plot
#'
#' 
#' @param data .
#' @param dep .
#' @param indep .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$scatter} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
regplot <- function(
    data,
    dep,
    indep) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("regplot requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if ( ! missing(indep)) indep <- jmvcore::resolveQuo(jmvcore::enquo(indep))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(indep), indep, NULL))


    options <- regplotOptions$new(
        dep = dep,
        indep = indep)

    analysis <- regplotClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

